version: '3'

services:
  tomcat:
    build: .
    env_file: .env
    environment:
      - MYSQL_HOST=db
    volumes:
      - ./webapp/:/usr/local/tomcat/webapps/LEA/
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      - MYSQL_HOST=db
    volumes:
      - db_data:/var/lib/mysql
      - ./jlea-2.0.sql:/docker-entrypoint-initdb.d/dump.sql

  web:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot:/etc/nginx/certs
    links:
      - tomcat
      - certbot
    depends_on:
      - tomcat
      - certbot

  certbot:
    build:
        context: .
        dockerfile: Cert.Dockerfile
    volumes:
      - certbot:/etc/nginx/certs

volumes:
  db_data:
  certbot:
